INITIAL_BACKGROUND = r"D:\Projects\Python-studies\shop_shop_manager\images\backgrounds\shop_shop_manager.png"
TOWN_BACKGROUND = r"D:\Projects\Python-studies\shop_shop_manager\images\backgrounds\town_background_one.png"
HOME_BACKGROUND = r"D:\Projects\Python-studies\shop_shop_manager\images\backgrounds\home_background.png"
SHOP_BACKGROUND = r"D:\Projects\Python-studies\shop_shop_manager\images\backgrounds\shop_background.png"
PAPER_BACKGROUND = r"D:\Projects\Python-studies\shop_shop_manager\images\backgrounds\paper_background.png"
